// Generated by LiveScript 1.2.0
(function(){
  var inf;
  inf = function(obj){
    console.log(obj);
    return $('.log').append(JSON.stringify(obj, void 8, 2) + "<br/>");
  };
  this.ws = new WebSocket("ws://localhost:8000/");
  ws.onmessage = function(evt){
    var obj;
    obj = JSON.parse(evt.data);
    return inf(obj);
  };
  ws.onclose = function(){
    return inf('closed');
  };
}).call(this);
