// Generated by LiveScript 1.2.0
(function(){
  var con, prt, srv, wss, clients, ser;
  con = require('connect');
  prt = require('serialport').SerialPort;
  srv = require('ws').Server;
  wss = new srv({
    port: 8000
  });
  this.decoder = {};
  this.setDecoder = function(dn){
    return this.decoder = require("./decoders/" + dn + ".js");
  };
  clients = [];
  ser = new prt("/dev/tty.usbmodem1d11", {
    baudrate: 9600
  }, false);
  ser.on('data', function(chunk){
    var msg, obj;
    msg = decoder.receive(chunk);
    if (msg != null) {
      return obj = decoder.decode(msg);
    }
  });
  ser.on('error', function(msg){
    return console.log("error: " + msg);
  });
  wss.on('connection', function(ws){
    clients += ws;
    return ws.on('message', function(m){
      return console.log(m);
    });
  });
  con().use(con['static'](__dirname)).listen(8080);
}).call(this);
