// Generated by LiveScript 1.3.1
(function(){
  var span, drop, length;
  span = require('prelude-ls').Str.span;
  drop = require('prelude-ls').drop;
  this.length = length = function(it){
    return it.length;
  };
  this.exspan = function(c, xs){
    var ref$, x, y;
    ref$ = span((function(it){
      return it !== c;
    }), xs), x = ref$[0], y = ref$[1];
    return [x, drop(length(c), y)];
  };
  this.toArray = function(x){
    return Array.prototype.slice.call(x);
  };
}).call(this);
