// Generated by LiveScript 1.2.0
(function(){
  var con, prt, srv, wss, d, ser;
  con = require('connect');
  prt = require('serialport').SerialPort;
  srv = require('ws').Server;
  wss = new srv({
    port: 8000
  });
  d = {};
  d.decode = function(d){
    return d;
  };
  ser = new prt("/dev/tty.usbmodem1d11", {
    baudrate: 9600
  }, false);
  ser.on('data', function(chunk){
    return ws.send(d.decode(chunk));
  });
  ser.on('error', function(msg){
    return console.log("error: " + msg);
  });
  wss.on('connection', function(ws){
    return ws.send('connected');
  });
  con().use(con['static'](__dirname)).listen(80);
}).call(this);
