// Generated by LiveScript 1.2.0
(function(){
  var ref$, dropWhile, span;
  ref$ = require('prelude-ls').Str, dropWhile = ref$.dropWhile, span = ref$.span;
  this.unpack = function(buf, chunk, sc, ec){
    var _buf, ref$, msg;
    _buf = dropWhile((function(it){
      return it !== sc;
    }), buf + chunk);
    if (_buf.indexOf(ec) === -1) {
      return [_buf, null];
    }
    ref$ = span((function(it){
      return it !== ec;
    }), _buf), msg = ref$[0], _buf = ref$[1];
    switch (false) {
    case msg[0] !== sc:
      return [_buf, msg];
    default:
      return [_buf, null];
    }
  };
}).call(this);
