// Generated by LiveScript 1.2.0
(function(){
  var ref$, dropWhile, takeWhile, buffer;
  ref$ = require('prelude-ls').Str, dropWhile = ref$.dropWhile, takeWhile = ref$.takeWhile;
  buffer = "";
  this.unchunk = function(chunk){
    var message;
    buffer += chunk;
    buffer = dropWhile((function(it){
      return it !== "$";
    }), buffer);
    message = takeWhile((function(it){
      return it !== ";";
    }), buffer);
    if (message.length >= 1) {
      buffer = dropWhile((function(it){
        return it !== ";";
      }), buffer);
      return message;
    }
  };
  this.decode = function(msg){
    return msg;
  };
}).call(this);
