// Generated by LiveScript 1.2.0
(function(){
  var ref$, dropWhile, span, moment, length, startChar, endChar, buffer, unpack;
  ref$ = require('prelude-ls').Str, dropWhile = ref$.dropWhile, span = ref$.span;
  moment = require('moment');
  length = function(it){
    return it.length;
  };
  startChar = ":";
  endChar = "\r";
  buffer = "";
  this.bufferSize = function(){
    return length(buffer);
  };
  this.flush = function(){
    return buffer = "";
  };
  this.receive = function(chunk){
    var msgs, ref$, buf, msg;
    if (this.bufferSize() >= 16000) {
      this.flush();
    }
    msgs = [];
    for (;;) {
      ref$ = unpack(buffer, chunk), buf = ref$[0], msg = ref$[1];
      buffer = buf;
      if (msg == null) {
        return msgs;
      }
      msgs.push(msg);
      chunk = "";
    }
  };
  unpack = function(buf, chunk){
    var _buf, ref$, msg;
    _buf = dropWhile((function(it){
      return it !== startChar;
    }), buf + chunk);
    if (_buf.indexOf(endChar) === -1) {
      return [_buf, null];
    }
    ref$ = span((function(it){
      return it !== endChar;
    }), _buf), msg = ref$[0], _buf = ref$[1];
    switch (false) {
    case msg[0] !== startChar:
      return [_buf, msg];
    default:
      return [_buf, null];
    }
  };
  this.decode = function(msg){
    var talker, sentence, _identifier, _depth, _corrDepth, _heave, _quality, _roll, _pitch;
    talker = "";
    sentence = "TSS-Sounder";
    _identifier = msg.substr(1, 6);
    _depth = msg.substr(8, 6);
    _corrDepth = msg.substr(15, 6);
    _heave = msg.substr(22, 5);
    _quality = msg.substr(27, 1);
    _roll = msg.substr(28, 5);
    _pitch = msg.substr(34);
    return {
      talker: talker,
      sentence: sentence,
      identifier: _identifier,
      depth: parseFloat(_depth) / 100.0,
      corrDepth: parseFloat(_corrDepth) / 100.0,
      heave: parseFloat(_heave) / 100.0,
      quality: _quality,
      pitch: parseFloat(_pitch) / 100.0,
      roll: parseFloat(_roll) / 100.0
    };
  };
}).call(this);
